export type Language =
    | 'Afrikaans'
    | 'Albanian'
    | 'Amharic'
    | 'Arabic'
    | 'Aramaic'
    | 'Armenian'
    | 'Aymara'
    | 'Azerbaijani'
    | 'Basque'
    | 'Belarusian'
    | 'Belizean Creole'
    | 'Bengali'
    | 'Berber'
    | 'Bislama'
    | 'Bosnian'
    | 'Bulgarian'
    | 'Burmese'
    | 'Catalan'
    | 'Chewa'
    | 'Chibarwe'
    | 'Chinese'
    | 'Comorian'
    | 'Croatian'
    | 'Czech'
    | 'Danish'
    | 'Dari'
    | 'Dutch'
    | 'Dzongkha'
    | 'English'
    | 'Estonian'
    | 'Fiji Hindi'
    | 'Fijian'
    | 'Filipino'
    | 'Finnish'
    | 'French'
    | 'Galician'
    | 'Georgian'
    | 'German'
    | 'Gilbertese'
    | 'Greek'
    | 'Guaraní'
    | 'Haitian Creole'
    | 'Hebrew'
    | 'Herero'
    | 'Hindi'
    | 'Hiri Motu'
    | 'Hungarian'
    | 'Icelandic'
    | 'Indonesian'
    | 'Irish'
    | 'Italian'
    | 'Jamaican Patois'
    | 'Japanese'
    | 'Kalanga'
    | 'Kazakh'
    | 'Khmer'
    | 'Khoekhoe'
    | 'Khoisan'
    | 'Kikongo'
    | 'Kinyarwanda'
    | 'Kirundi'
    | 'Korean'
    | 'Kwangali'
    | 'Kyrgyz'
    | 'Lao'
    | 'Latvian'
    | 'Lingala'
    | 'Lithuanian'
    | 'Lozi'
    | 'Luxembourgish'
    | 'Macedonian'
    | 'Malagasy'
    | 'Malay'
    | 'Maldivian'
    | 'Maltese'
    | 'Marshallese'
    | 'Mauritian Creole'
    | 'Mongolian'
    | 'Montenegrin'
    | 'Māori'
    | 'Nauru'
    | 'Ndau'
    | 'Ndonga'
    | 'Nepali'
    | 'New Zealand Sign Language'
    | 'Northern Ndebele'
    | 'Northern Sotho'
    | 'Norwegian Bokmål'
    | 'Norwegian Nynorsk'
    | 'Palauan'
    | 'Pashto'
    | 'Persian (Farsi)'
    | 'Polish'
    | 'Portuguese'
    | 'Quechua'
    | 'Romanian'
    | 'Romansh'
    | 'Russian'
    | 'Sami'
    | 'Samoan'
    | 'Sango'
    | 'Serbian'
    | 'Seychellois Creole'
    | 'Shona'
    | 'Sinhala'
    | 'Slovak'
    | 'Slovene'
    | 'Somali'
    | 'Sorani'
    | 'Sotho'
    | 'Southern Ndebele'
    | 'Southern Sotho'
    | 'Spanish'
    | 'Swahili'
    | 'Swazi'
    | 'Swedish'
    | 'Swiss German'
    | 'Tajik'
    | 'Tamil'
    | 'Tetum'
    | 'Thai'
    | 'Tigrinya'
    | 'Tok Pisin'
    | 'Tonga'
    | 'Tongan'
    | 'Tshiluba'
    | 'Tsonga'
    | 'Tswana'
    | 'Turkish'
    | 'Turkmen'
    | 'Tuvaluan'
    | 'Ukrainian'
    | 'Urdu'
    | 'Uzbek'
    | 'Venda'
    | 'Vietnamese'
    | 'Xhosa'
    | 'Zimbabwean Sign Language'
    | 'Zulu'
